# Generated by Django 5.2.4 on 2025-08-21 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_categoria_descripcion_categoria_slug'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='categorias.categoria'),
            preserve_default=False,
        ),
    ]
