# Generated by Django 5.2.4 on 2025-08-21 17:43

from django.db import migrations

def seed_categorias(apps, schema_editor):
    Categoria = apps.get_model('categorias', 'Categoria')
    nombres = [
        "Aprendizaje Automático",
        "Redes Neuronales",
        "Procesamiento de Lenguaje Natural",
        "Visión por Computadora",
        "Robótica e IA",
        "Ética e IA Responsable",
        "IA Generativa",
        "Big Data y Analítica",
    ]
    for nombre in nombres:
        Categoria.objects.get_or_create(nombre=nombre)

def unseed_categorias(apps, schema_editor):
    Categoria = apps.get_model('categorias', 'Categoria')
    Categoria.objects.filter(nombre__in=[
        "Aprendizaje Automático",
        "Redes Neuronales",
        "Procesamiento de Lenguaje Natural",
        "Visión por Computadora",
        "Robótica e IA",
        "Ética e IA Responsable",
        "IA Generativa",
        "Big Data y Analítica",
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('categorias', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(seed_categorias, reverse_code=unseed_categorias),
    ]

